### ISSUE TITLE
Uncaught error when axios retry is used

### ISSUE THREAD

**Issue by adambullmer** [nuxt-community/auth-module#1075]
### Version
module: `5.0.0-1613647907.37b1156`
nuxt: `2.14.12`

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt configuration

```js
export default {
  axios: {
    retry: true,
  },
}
```

## Reproduction
> :warning: without a minimal reproduction we won't be able to look into your issue

Reproducible example: https://codesandbox.io/s/busy-gareth-vewyu

#### What is expected?

When the native @nuxtjs/axios module is configured for retrying, the auth module should still work on a retried request.

#### What is actually happening?

An error is thrown on SSR regarding checking the Authorization header. If using nuxt error pages, this will instead render an error page instead of the intended page. This is due to getting a different type config object structure in the headers.

#### Steps to reproduce

In the [above example](https://codesandbox.io/s/busy-gareth-vewyu), just visiting the home page directly by address bar or refreshing the page will yield the server error.

```
 ERROR  Cannot read property 'Authorization' of undefined             18:50:18

  at RequestHandler._requestHasAuthorizationHeader (server.js:4001:35)
  at interceptor.axios.interceptors.request.use (server.js:3978:28)
```

## Additional information

I believe the root of the bug is here, where deep object accessors don't check that the previous key exists: https://github.com/nuxt-community/auth-module/blob/dev/src/inc/request-handler.ts#L126

I've made a patch locally to not be blocked by a release:

```patch
diff --git a/dist/runtime.js b/dist/runtime.js
index 62e6ede5118ed93c1135ff13f40e3682e023842e..a3d9a7d3de48e8ca62fb19a01546c3a6b75e0df7 100644
--- a/dist/runtime.js
+++ b/dist/runtime.js
@@ -813,7 +813,9 @@ class RequestHandler {
     return config;
   }
   _requestHasAuthorizationHeader(config) {
-    return !!config.headers.common[this.scheme.options.token.name];
+    return config.headers.common
+      ? !!config.headers.common[this.scheme.options.token.name]
+      : !!config.headers[this.scheme.options.token.name];
   }
 }
 
diff --git a/dist/runtime.mjs b/dist/runtime.mjs
index d31247774cf349475b81392852771de6995d48c7..9acc35841b61c6a4661571c2961b7f5561741f0e 100644
--- a/dist/runtime.mjs
+++ b/dist/runtime.mjs
@@ -802,7 +802,9 @@ class RequestHandler {
     return config;
   }
   _requestHasAuthorizationHeader(config) {
-    return !!config.headers.common[this.scheme.options.token.name];
+    return config.headers.common
+      ? !!config.headers.common[this.scheme.options.token.name]
+      : !!config.headers[this.scheme.options.token.name];
   }
 }
 ```

## Checklist
* [x]  I have tested with the latest Nuxt version and the issue still occurs
* [x]  I have tested with the latest module version and the issue still occurs
* [x]  I have searched the issue tracker and this issue hasn't been reported yet

### What is actually happening?

![Screen Shot 2021-02-24 at 1 11 22 PM](https://user-images.githubusercontent.com/3661307/109052961-d3ca6100-76a1-11eb-95c1-a035d93e7f7f.png)

### Performance analysis?

n/a

**Comment by yns-ph** [comment]
@rico-ocepek I also encountered this issue while setting up the auth for local login. For workarounds, use @nuxt/auth which is the previous version on nuxt auth(4.9.1) instead of @nuxt/auth-next.

**Comment by mattprado21** [comment]
@rico-ocepek I also encountered this issue while setting up the auth for local login. For workarounds, use @nuxt/auth which is the previous version on nuxt auth(4.9.1) instead of @nuxt/auth-next.

**Comment by bmulholland** [comment]
We recently upgraded axios, can you please try the latest auth-next and see if this is resolved?

**Comment by bmulholland** [comment]
Also, for SSR, please check everything listed in https://github.com/nuxt-community/auth-module/issues/1197
