### ISSUE TITLE
ERROR  Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by frederikpyt** [nuxt-community/auth-module#1205]
I have an issue where if i reload the page in my nuxt app i get it redirects me to another page (The same page no matter which page i was actually on). I want to fix this.

I've actually fixed it by doing so in my `store/index.js`
```
async nuxtServerInit ({
    state
  }, {
    req
  }) {
    let auth = null
    if (req.headers.cookie) {
      try {
        auth = await this.$axios.$get('/user')
      } catch (err) {
        // eslint-disable-next-line no-unused-vars
        auth = null
      }
    }

    this.$auth.setUser(auth)
  },
```

However this spams my server console with the following:
```
ERROR  Cannot set headers after they are sent to the client
   at new NodeError (node:internal/errors:329:5)
   at ServerResponse.setHeader (node:_http_outgoing:573:11)
   at Storage.setCookie (server.js:3694:20)
   at Storage.setUniversal (server.js:3555:10)
   at Storage.syncUniversal (server.js:3582:12)
   at Token._syncToken (server.js:4289:26)
   at Token.sync (server.js:4241:24)
   at Oauth2Scheme.check (server.js:4575:30)
   at server.js:4177:23
```

Commenting out the `this.$auth.setUser(auth)` makes the errors go away, but also the reloading stops working as intended.
I've also tried replacing `this.$auth.setUser(auth)` with:
```
state.auth.user = auth
state.auth.loggedIn = (auth !== null)
```

it produced the same errors

**Comment by Msmicha200** [comment]
Try to use default endpoint property for getting user. Or you have any reasons not to use it?

**Comment by frederikpyt** [comment]
> Try to use default endpoint property for getting user. Or you have any reasons not to use it?

Same issue

**Comment by frederikpyt** [comment]
I found a temporary fix, adding this to my login redirect page fixes it:
```
created () {
    if (this.$auth.loggedIn) {
      if (this.$auth.$storage.getCookies()['auth.redirect']) {
        this.$router.replace(this.$auth.$storage.getCookies()['auth.redirect'])
      }
    }
  }
```

**Comment by frederikpyt** [comment]
> Hi @frederikpyt! Can you share your auth config?

auth: {    redirect: {      login: '/',      logout: '/',      callback: '/auth',      home: '/overview'    },    strategies: {      freyrsoft: {        scheme: 'oauth2',        endpoints: {          authorization: process.env.PASSPORT_URL + '/oauth/authorize',          token: process.env.PASSPORT_URL + '/oauth/token',          userInfo: process.env.PASSPORT_URL + '/api/user',          logout: process.env.PASSPORT_URL + '/logout'        },        token: {          property: 'access_token',          type: 'Bearer',          maxAge: 60 * 60 * 24 // 1 day        },        refreshToken: {          property: 'refresh_token',          maxAge: 60 * 60 * 24 * 10 // 10 days        },        responseType: 'code',        grantType: 'authorization_code',        accessType: 'offline',        clientId: process.env.PASSPORT_CLIENT_ID,        codeChallengeMethod: 'S256',        scope: null,        autoLogout: false      }    }  }

**Comment by frederikpyt** [comment]
> Hi @frederikpyt! Can you share your auth config?
> 
> EDIT: Also the responses of your `login` and `user` endpoints.
I can't seem to find the response of my login endpoint? Any ideas?
