### ISSUE TITLE
not work with nuxt 3

### ISSUE THREAD

**Issue by n4an** [nuxt-community/auth-module#1323]
Cannot start nuxt

**Comment by d4rkr3pt0r** [comment]
Same here. getting the following error when I use `npm run dev`:
```
 ERROR  Cannot start nuxt:  URL is required with Laravel Sanctum!                                             00:20:24

  at laravelSanctum (node_modules\@nuxtjs\auth-next\dist\module.js:370:11)
  at resolveStrategies (node_modules\@nuxtjs\auth-next\dist\module.js:456:7)
  at Object.authModule (node_modules\@nuxtjs\auth-next\dist\module.js:512:40)
  at installModule (/D:/Programming/MyApp/app/node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (/D:/Programming/MyApp/app/node_modules/nuxt3/dist/index.mjs:817:11)
  at async load (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/dev.mjs:6762:9)
  at async Object.invoke (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/dev.mjs:6793:5)
  at async _main (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/index.mjs:417:7)


 ERROR  [unhandledRejection] Cannot read property 'hooks' of undefined                                        00:20:24

  at Object.wrappedModule (/D:/Programming/MyApp/app/node_modules/@nuxt/kit/dist/index.mjs:1092:13)
  at Object.installModule (/D:/Programming/MyApp/app/node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at Object.axiosModule (node_modules\@nuxtjs\axios\lib\module.js:141:10)
  at installModule (/D:/Programming/MyApp/app/node_modules/@nuxt/kit/dist/index.mjs:1196:17)
  at initNuxt (/D:/Programming/MyApp/app/node_modules/nuxt3/dist/index.mjs:817:11)
  at async load (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/dev.mjs:6762:9)
  at async Object.invoke (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/dev.mjs:6793:5)
  at async _main (/D:/Programming/MyApp/app/node_modules/nuxi/dist/chunks/index.mjs:417:7)

√ Generated nuxt.d.ts
```

**Comment by bmulholland** [comment]
We haven't had time to investigate this - so more information, investigation, and PRs would all be very welcomed.

**Comment by hartmut-co-uk** [comment]
Hi, did anyone take a look in the meantime?
Any gut feeling how much effort it will be to support nuxt3?
Any blockers (I understand pinia already is supported and therefore can be used?)
Is this going to be built/released with/as [v5](https://github.com/nuxt-community/auth-module/releases/tag/5.0.0-dev)?

**Comment by Dreaming-Codes** [comment]
> Did you tried it with [Nuxt Bridge](https://v3.nuxtjs.org/getting-started/bridge)?
> 
> Do you mind submitting your findings or updates here please? https://isnuxt3ready.owln.ai/ This way, the community will have a faster and simpler way of spotting the actual status of some packages.

Works perfectly on nuxt bridge

**Comment by mrleblanc101** [comment]
Should probably make sure v5 work on both Nuxt 2 and Nuxt 3 when it launch. Otherwise v5 should focus on Nuxt 2 and a v6 should be created for Nuxt 3

**Comment by hartmut-co-uk** [comment]
> It will certainly be part of v5/auth-next.

@bmulholland which branch would that be then? 
`dev`?

**Comment by bmulholland** [comment]
Yes, auth-next is the dev branch

**Comment by mrleblanc101** [comment]
Si v5 will still be compatible with Nuxt 2 or supporting Nuxt 3 has breaking change ?

**Comment by bmulholland** [comment]
I don't know yet

**Comment by mrleblanc101** [comment]
IMHO, v5 should support Nuxt 2 as a lot of people are already using it with `@nuxtjs/auth-next`. They would be left with no alternative if v5 only support Nuxt 3. 

If there is breaking change to support Nuxt 3,I think v5 should be finished with only Nuxt 2 support and a new v6 should be started for Nuxt 3.

**Comment by bmulholland** [comment]
@mrleblanc101 Thanks, I understood your point in your original comment. We'll make sure we provide appropriate nuxt version support for whatever is needed. Your PRs to help out are welcomed.

**Comment by hartmut-co-uk** [comment]
@bmulholland is the `yarn dev` supposed to compile and run on `dev` branch?
Is any particular node version required? (I'm using `v16.13.0`)

```
Module build failed (from ./node_modules/ts-loader/index.js):                                                                                                                                                                                                    friendly-errors 17:59:23
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/Users/hartmut/dev/git/examples/nuxt/auth-module/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/Users/hartmut/dev/git/examples/nuxt/auth-module/node_modules/ts-loader/dist/index.js:14:21)
                                                                                                                                                                                                                                                                 friendly-errors 17:59:23
 @ ./demo/pages/oauth2RefreshTest.vue?vue&type=script&lang=ts& 1:0-298 1:314-317 1:319-614 1:319-614
 @ ./demo/pages/oauth2RefreshTest.vue
 @ ./demo/.nuxt/router.js
 @ ./demo/.nuxt/index.js
 @ ./demo/.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./demo/.nuxt/client.js
```
⚠️ Note for M1 users: in case anyone else runs into, I'm with an M1 and had trouble with yarn install with `playwright` - I was able to make it work by [switching to x64 architecture environment](https://www.jurnalanas.com/node-js-mac-m1/).

**Comment by bmulholland** [comment]
@hartmut-co-uk Honestly I haven't fired it up myself for some time, and so basic fixes for `yarn dev` may well be needed.

Re: playwright, I'm hoping that upgrading it will add M1 support.

**Comment by hartmut-co-uk** [comment]
> Re: playwright, I'm hoping that upgrading it will add M1 support.
I found https://github.com/microsoft/playwright/issues/7646#issuecomment-880797427 but using `playwright@next` didn't solve the build for me. It was still breaking, I think not because of playwright anymore but just failed without any error message 🎁 😅

**Comment by toniengelhardt** [comment]
For me it doesn't work with Nuxt Bridge. As soon as I add `middleware: ['auth']` to router in `nuxt.config.js` like so:

```js
  router: {
    base: '/',
    middleware: ['auth'],
    linkActiveClass: 'active',
    linkExactActiveClass: 'exact-active',
    extendRoutes(routes) {
      routes.push({
        path: '/',
        redirect: '/write',
      })
    }
  }
```

I get the following error when I try to start the dev server with `yarn dev`:

<img width="850" alt="Screen Shot 2021-11-27 at 15 55 14" src="https://user-images.githubusercontent.com/2703233/143688222-c4f97de4-8ba1-47b8-9aa2-2ed1bc15cd2d.png">

If I remove `middleware: ['auth']` the error disappears.

Digging into the source file that causes the error `node_modules/@nuxt/bridge/dist/chunks/module2.mjs`:

![Screen Shot 2021-11-27 at 15 57 22](https://user-images.githubusercontent.com/2703233/143688312-0e1f5992-8eee-4723-84ed-481db43093fe.png)

it happens in `map((m) => ...)` where `m` is simply the string `"auth"` and therefore `m.src` is undefined.

Is this a problem of the `@nuxt/auth` package or Nuxt Bridge?

**Comment by bmulholland** [comment]
IMO the config format you included should be supported by nuxt, so I think it's an issue with nuxt bridge - could you please file an issue over there?

**Comment by toniengelhardt** [comment]
@bmulholland yes will do, thanks!

**Comment by TimVanHerwijnen** [comment]
@toniengelhardt:
> For me it doesn't work with Nuxt Bridge.

I have tested it with [Nuxt 3 Bridge](https://v3.nuxtjs.org/getting-started/bridge) and it's working like it's supposed to after following the guide.

Notice that `middleware: ['auth']` is supposed to be in the `router` object like so:
```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  // ...
  router: {
    middleware: [
      'auth',
    ],
  }
  // ...
})
```

The only bug I'm experiencing is when I log in and refresh the page the middleware can't detect I'm logged in and redirects me to the login page. However, the store is correct and has the fetched user object and has the `loggedIn: true`. I think this has to do with the breaking changes to how middlewares work in Nuxt3. I may try and create a middleware suited for Nuxt 3. If I succeed I will update you with the discoveries I made.

<details>
  <summary>My full `nuxt.config.js`</summary>

  ```js
  import { defineNuxtConfig } from '@nuxt/bridge'

  export default defineNuxtConfig({
    // Global page headers: https://go.nuxtjs.dev/config-head
    head: {
      title: 'auth-test',
      htmlAttrs: {
        lang: 'en'
      },
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { hid: 'description', name: 'description', content: '' },
        { name: 'format-detection', content: 'telephone=no' }
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
      ]
    },

    // Global CSS: https://go.nuxtjs.dev/config-css
    css: [
      'ant-design-vue/dist/antd.css'
    ],

    // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
    plugins: [
      '@/plugins/antd-ui'
    ],

    // Auto import components: https://go.nuxtjs.dev/config-components
    components: true,

    // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
    buildModules: [
    ],

    // Modules: https://go.nuxtjs.dev/config-modules
    modules: [
      // https://go.nuxtjs.dev/axios
      '@nuxtjs/axios',
      // https://dev.auth.nuxtjs.org/
      '@nuxtjs/auth-next'
    ],

    // Axios module configuration: https://go.nuxtjs.dev/config-axios
    axios: {
      prefix: '/api/',
      credentials: true,
      proxy: true,
    },

    proxy: {
      '/api/': { target: 'http://localhost:8000/', pathRewrite: { '^/api/': '' } }
    },

    // Auth module configuration: https://dev.auth.nuxtjs.org/
    auth :{
      strategies: {
        local: {
          token: {
            property: 'token',
            global: true,
            required: true,
            type: 'Bearer'
          },
          user: {
            property: 'user',
            autoFetch: true
          },
          endpoints: {
            login: { url: '/login', method: 'post' },
            logout: { url: '/logout', method: 'get' },
            user: { url: '/user', method: 'get' }
          }
        }
      },
      // redirect: {
      //   login: '/login',
      //   logout: '/',
      //   callback: '/login',
      //   home: '/profile'
      // }
    },

    router: {
      middleware: [
        'auth',
      ],
    },

    // Build Configuration: https://go.nuxtjs.dev/config-build
    build: {
      //
    }
  })
  ```
</details>

**Comment by toniengelhardt** [comment]
Hey @TimVanHerwijnen, thanks for digging in!

I just raised the issue in the Nuxt repo (nuxt/bridge#164) and created a reproduction:

Github: https://github.com/toniengelhardt/nuxt-bridge-debug
CodeSandBox: https://codesandbox.io/s/cool-benji-c0ryp

Note that the router config also includes the middleware setting as specified in the docs.

When I first tried to reproduce the problem from scratch I also didn't see it at first, but when I added more packages and modules from my project repo it showed up, so it seems like it is clashing with some other module or package.

**Comment by toniengelhardt** [comment]
**Update**

The previous issue has been fixed in Nuxt Bridge, but now I get this one:

<img width="850" alt="Screen Shot 2021-12-12 at 23 57 58" src="https://user-images.githubusercontent.com/2703233/145734919-dbbf8c28-d458-4d39-8b73-b7da29cd0b2c.png">

I think that is because the middleware is now actually loaded, but not compatible yet...

**Comment by TimVanHerwijnen** [comment]
I am now taking the refresh (jwt) approach and got the auth module completely working now without any issues. 
So I am convinced this is a configuration or a vite error.
```json
"dependencies": {
  "@nuxtjs/auth-next": "^5.0.0-1637745161.ea53f98",
  "@nuxtjs/axios": "^5.13.6",
  "ant-design-vue": "^1.7.8",
  "core-js": "^3.15.1",
  "nuxt-edge": "^2.16.0-27322574.c1d02ea3"
},
"devDependencies": {
  "@nuxt/bridge": "npm:@nuxt/bridge-edge"
}
```
#### What I've tested and is working as supposed:
- I can make calls to my auth api and get tokens when logging in.
- Tokens are stored in cookie and `loggedIn` is set to `true`.
- User is successfully obtained.
- Middleware works: I can access login page only when unauthenticated and profile only when authenticated. If not authenticated/unauthenticated it redirects me to configured redirects.
- When token is expired it automatically refreshes token or logs you out if refresh token is invalid/revoked. (`resetOnError` must be `true`)

<details>
  <summary>My updated `nuxt.config.js`</summary>
  
```js
import { defineNuxtConfig } from '@nuxt/bridge'

export default defineNuxtConfig({
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'fusionauth-test',
    htmlAttrs: {
      lang: 'en'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ]
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    'ant-design-vue/dist/antd.css'
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    '@/plugins/antd-ui',
    '@/plugins/axios',
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://dev.auth.nuxtjs.org/
    '@nuxtjs/auth-next'
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {
    baseURL: 'http://localhost:8080/', // Nuxt host url
    credentials: true,
    proxy: true,
  },

  proxy: {
    '/auth/': { target: process.env.FUSIONAUTH_URL, pathRewrite: { '^/auth/': '' } }
  },

  // Auth module configuration: https://dev.auth.nuxtjs.org/
  auth :{
    localStorage: false,
    resetOnError: true,
    strategies: {
      local: {
        scheme: 'refresh',
        tokenType: 'JWT',
        token: {
          property: 'token',
          maxAge: 60 * 10, // 10 Minutes
          global: true,
        },
        refreshToken: {
          tokenRequired: true,
          property: 'refreshToken',
          data: 'refreshToken',
          maxAge: 60 * 60 * 24 * 30 // 30 Days
        },
        user: {
          property: 'user',
          autoFetch: true
        },
        endpoints: {
          login: { url: 'auth/api/login', method: 'post' },
          refresh: { url: 'auth/api/jwt/refresh', method: 'post' },
          logout: { url: 'auth/api/logout', method: 'post' },
          user: { url: 'auth/api/user', method: 'get' }
        },
        autoLogout: false
      }
    },
    redirect: {
      login: '/login',
      logout: '/',
      home: '/profile',
      callback: '/login',
    }
  },

  router: {
    middleware: [
      'auth',
    ],
  },

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    //
  }
})

```
  
</details>

**Comment by toniengelhardt** [comment]
Interesting, so it probably is a VIte bug. I also have other errors when disabling Vite in my project, but I'll try to resolve and confirm that it works without Vite.

**Comment by mittche** [comment]
> Interesting, so it probably is a Vite bug. I also have other errors when disabling Vite in my project, but I'll try to resolve and confirm that it works without Vite and then raise an issue in the Nuxt repo.

of course problem is with vite as long as it hast replaced previous what it was (webpack)

**Comment by bmulholland** [comment]
Quick update: I upgraded packages and fixed `yarn dev` (cc @hartmut-co-uk); hopefully that's a good first step here.

I've also added a request for assistance with some specific tasks over at https://github.com/nuxt-community/auth-module/issues/1393. If you find anything specific that is needed -- or helpful -- for nuxt bridge or nuxt 3, please let me know and I'll add it to the list.

**Comment by hartmut-co-uk** [comment]
👍  I can now run and start in dev mode from latest `dev` branch without any errors. Also can access the page locally. 
I also was able to login with oauth2 and OpenIDConnect using `admin:admin`.

So much for quick feedback.

**Comment by hartmut-co-uk** [comment]
running `yarn jest` from local all tests are failing, getting those 2 types of errors:

![image](https://user-images.githubusercontent.com/10864443/148137398-9cd27be0-569f-4032-b1bb-57b5ad39c619.png)
...
![image](https://user-images.githubusercontent.com/10864443/148137463-b93bc733-4033-46b8-a25c-affa2fce36d3.png)

I can see gh actions pass on _dev_ branch, is there anything specific to setup to get this working?

**Comment by bmulholland** [comment]
Ah I'd added a note on running tests to the readme, but it was stuck in a branch. Just pushed it, does this help? https://github.com/nuxt-community/auth-module#development

**Comment by hartmut-co-uk** [comment]
thx, all tests pass!

**Comment by lacorde** [comment]
@hartmut-co-uk Good news ! Are you on Nuxt-Bridge or Nuxt 3 ?

**Comment by bmulholland** [comment]
Created https://github.com/nuxt-community/auth-module/issues/1519
And https://github.com/nuxt-community/auth-module/issues/1520

Those are small sample projects that will help to confirm if the basics work from scratch.

**Comment by linhherrera96** [comment]
![image](https://user-images.githubusercontent.com/35018289/155652956-e682b6d8-3cc5-438a-9a72-e17823b3501f.png)

Help me, when i import '@nuxtjs/auth-next' in nuxt.config.ts get this error (Nuxt 3)

**Comment by mrleblanc101** [comment]
@linhherrera96 Use Nuxt 2 as Nuxt 3 is still in Beta or wait for a Nuxt 3 version of this plugin.

**Comment by linhherrera96** [comment]
> @linhherrera96 Use Nuxt 2 as Nuxt 3 is still in Beta or wait for a Nuxt 3 version of this plugin.

so is there any library to replace it? Currently I am using Nuxt 3 to do project.

**Comment by sneakylenny** [comment]
> so is there any library to replace it? Currently I am using Nuxt 3 to do project.

So I've noticed on the [Nuxt 3 roadmap](https://v3.nuxtjs.org/community/roadmap/#core-modules) they are working on it, but in a private beta. So I think we'll have to wait since there are no alternatives yet.
My project is still stuck in Nuxt bridge for this and more reasons.

**Comment by toniengelhardt** [comment]
@TimVanHerwijnen do you have nuxt/auth running with Bridge and Vite? 

I'm having a middleware issue mentioned here: https://github.com/nuxt-community/auth-module/issues/1519

**Comment by sneakylenny** [comment]
@toniengelhardt I do have it running with `@nuxtjs/auth-next: 5.0.0-1648802546.c9880dc` and `@nuxt/bridge: npm:@nuxt/bridge-edge@3.0.0-27488730.0cbc9cb` without any issues but I don't use Vite. 

**Edit:** 
Tested in both dev and prod

**Comment by justindasilva** [comment]
Anyone have this running with Nuxt Bridge?
If so, are there specific package versions that need to be set?

Currently seeing this:
```
 ERROR  [worker reload] [worker init] The requested module 'file:///Users/justin.dasilva/Sites/mercatus/cm/config-manager/app/node_modules/defu/dist/defu.mjs' does not provide an export named 'createDefu'

  import { createDefu } from 'node_modules/defu/dist/defu.mjs';
  ^^^^^^^^^^
  SyntaxError: The requested module 'node_modules/defu/dist/defu.mjs' does not provide an export named 'createDefu'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async loadESM (node:internal/process/esm_loader:88:5)
  at async handleMainPromise (node:internal/modules/run_main:65:12)

```

**Comment by aborn** [comment]
[OpenID-Connect(OIDC) integration module for nuxt 3.0](https://github.com/aborn/nuxt-openid-connect).

**Comment by phillipmohr** [comment]
> [OpenID-Connect(OIDC) integration module for nuxt 3.0](https://github.com/aborn/nuxt-openid-connect).

Thanks! I looked into the examples. But how would I restrict certain pages? For example:
pages
  - index.vue (< this is public)
  - admin (< these are all restricted and only visible after login)
    - index.vue
    - settings.vue

**Comment by aborn** [comment]
> OpenID-Connect(OIDC) integration module for nuxt 3.0

[This exampe page](https://github.com/aborn/playgrounds/blob/main/nuxt-openid-connect-demo/pages/index.vue) shows how to use it in restricted pages. For public pages, you don't need ref: *const { $oidc } = useNuxtApp()* at setup script, which page can't get use info.

**Comment by amery** [comment]
anyone using [@nxutjs-alt/auth](https://www.npmjs.com/package/@nuxtjs-alt/auth) in the meantime? I'm getting `undefined` when trying to access `useNuxtApp().$auth` on a form submit function

**Comment by Slaknoah** [comment]
I only got it working with Vite + Nuxt Bridge Next by adding this to my nuxt config. Hope it helps someone out.
```
vite: { 
    optimizeDeps: {
      include: [
        'cookie'
      ]
    }
  }
```

**Comment by toniengelhardt** [comment]
@Slaknoah could you share your full config? That would be amazing!

**Comment by Arturexe** [comment]
Is there a replacement now?

**Comment by amery** [comment]
> Is there a replacement now?

https://www.npmjs.com/package/@nuxtjs-alt/auth works fine, but it's diverged from slightly from @nuxtjs/auth
