### ISSUE TITLE
I've got error with nuxt v3: Cannot set properties of undefined (setting 'auth')

### ISSUE THREAD

**Issue by adminoid** [nuxt-community/auth-module#1719]
### Version

module: 5.0.0-1648802546.c9880dc
nuxt: ^3.0.0-27467056.93c4dfe

#### [mode](https://nuxtjs.org/api/configuration-mode): 

- [x] universal
- [ ] spa

## Reproduction

> Cannot set properties of undefined (setting 'auth')
>  at $id_9de234f6 (file://./.nuxt/dist/server/server.mjs:5911:36)
>  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:8876:3)

#### What is actually happening?
I've got a error when run `yarn dev` command

## Checklist

- [x] I have tested with the latest Nuxt version and the issue still occurs
- [x] I have tested with the latest module version and the issue still occurs
- [x] I have searched the issue tracker and this issue hasn't been reported yet

### Steps to reproduce

Just install  @nuxtjs/auth-next, run yarn dev and see the error.

**Comment by ninebolt6** [comment]
@nuxtjs/auth-next is not compatible with nuxt3.
There is a rewrite of this module ongoing. Check this [roadmap](https://v3.nuxtjs.org/community/roadmap/#-core-modules)

FYI: https://github.com/nuxt/framework/discussions/3447#discussioncomment-2476970
