### ISSUE TITLE
TypeError: request.charCodeAt is not a function

### ISSUE THREAD

**Issue by tanggaowei** [nuxt-community/auth-module#229]
[16:56:06] TypeError: request.charCodeAt is not a function
at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:408:15)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:574:20)
at Nuxt.resolveModule (F:\Javaspace\general\general-card-www\node_modules\_nuxt-edge@2.0.0-25571241.61c0976@nuxt-edge\dist\nuxt.js:2178:35)
at Nuxt.resolveAlias (F:\Javaspace\general\general-card-www\node_modules\_nuxt-edge@2.0.0-25571241.61c0976@nuxt-edge\dist\nuxt.js:2193:29)
at Array.map (<anonymous>)
at Builder.watchFiles (F:\Javaspace\general\general-card-www\node_modules\_nuxt-edge@2.0.0-25571241.61c0976@nuxt-edge\dist\nuxt.js:3878:37)
at Builder.webpackDev (F:\Javaspace\general\general-card-www\node_modules\_nuxt-edge@2.0.0-25571241.61c0976@nuxt-edge\dist\nuxt.js:3829:10)
at Promise (F:\Javaspace\general\general-card-www\node_modules\_nuxt-edge@2.0.0-25571241.61c0976@nuxt-edge\dist\nuxt.js:3755:23)

**Comment by manniL** [comment]
Fixed with https://github.com/nuxt/nuxt.js/pull/3771#pullrequestreview-147657622

**Comment by tanggaowei** [comment]
Thanks for all!

**Comment by bharaths6** [comment]
I got this error on `npm start`

`npm run ng serve `  worked for me
