### ISSUE TITLE
body-parser should be in dependencies not devDependencies

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/auth-module#430]
### Version

[v4.8.1](https://github.com/auth-module/releases/tag/v4.8.1)

### Reproduction link

[http://url.com](http://url.com)

### Steps to reproduce

Try running a basic example without body-parser installed

```
Error while initializing nuxt: { /var/task/node_modules/@nuxtjs/auth/lib/providers/_utils.js:1
Error: Cannot find module 'body-parser'
```

### What is expected ?

It should work

### What is actually happening?

Nuxt can't find the body-parser module

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c401">#c401</a>)</em></sub></div>

**Comment by nzakas** [comment]
This is causing a problem when trying to deploy to ZEIT Now. Since `body-parser` is in `devDependencies`, the Now builder doesn't include it and therefore I get this error:

```
START RequestId: 2d8e5238-1967-4bb7-a6d8-6403abc144a0 Version: $LATEST
2019-09-02T18:59:21.306Z	2d8e5238-1967-4bb7-a6d8-6403abc144a0	λ Error while initializing nuxt: { /var/task/node_modules/@nuxtjs/auth/lib/providers/_utils.js:1
Error: Cannot find module 'body-parser'
Require stack:
- /var/task/node_modules/@nuxtjs/auth/lib/providers/_utils.js
- /var/task/node_modules/@nuxtjs/auth/lib/providers/github.js
- /var/task/node_modules/@nuxtjs/auth/lib/module/index.js
- /var/task/node_modules/@nuxt/core/dist/core.js
- /var/task/now__launcher.js
- /var/runtime/node_modules/awslambda/index.js
    at Object.<anonymous> (/var/task/node_modules/@nuxtjs/auth/lib/providers/_utils.js:2:20)
    at Object.Module._extensions..js (module.js:663:10)
  code: 'MODULE_NOT_FOUND',
  requireStack: 
   [ '/var/task/node_modules/@nuxtjs/auth/lib/providers/_utils.js',
     '/var/task/node_modules/@nuxtjs/auth/lib/providers/github.js',
     '/var/task/node_modules/@nuxtjs/auth/lib/module/index.js',
     '/var/task/node_modules/@nuxt/core/dist/core.js',
     '/var/task/now__launcher.js',
     '/var/runtime/node_modules/awslambda/index.js' ] }
END RequestId: 2d8e5238-1967-4bb7-a6d8-6403abc144a0
REPORT RequestId: 2d8e5238-1967-4bb7-a6d8-6403abc144a0	Duration: 308.28 ms	Billed Duration: 400 ms 	Memory Size: 3008 MB	Max Memory Used: 105 MB	
RequestId: 2d8e5238-1967-4bb7-a6d8-6403abc144a0 Process exited before completing request
```

This is blocking for anyone trying to deploy on ZEIT Now while using this module.

**Comment by manniL** [comment]
Correct. PR welcome ☺️

**Comment by nzakas** [comment]
Done: https://github.com/nuxt-community/auth-module/pull/441
