### ISSUE TITLE
Cannot redirect after setUserToken

### ISSUE THREAD

**Issue by Cengkaruk** [nuxt-community/auth-module#531]
Nuxt's context redirection not working after setUserToken promise. Here the error log

```
(node:89375) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:535:11)
    at Storage.setCookie (server.js:1266:20)
    at Storage.setUniversal (server.js:1078:10)
    at Auth.setToken (server.js:587:26)
    at Auth.reset (server.js:562:12)
    at server.js:418:16
    at Auth.callOnError (server.js:710:7)
    at server.js:552:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Example code
```
async asyncData({ $auth, redirect }) {
     $auth.setUserToken(accessToken).then(() => {
        redirect('/home')
      })
  }
```

**Comment by mean-cj** [comment]
Hello @Cengkaruk 

How do you do ?

I found same problem
after i call setUserToken() , nuxt@auth force to redirect to home

Thank.

**Comment by mean-cj** [comment]
My solution
```
-----------------
auth: {
    watchLoggedIn: false,
}
-----------------
$auth.setUserToken(accessToken).then(() => {
        redirect('/home')
 })

```
